### ISSUE TITLE
After building firmware with Platformio Matrix stays dark

### ISSUE THREAD

**Issue by Truddel** [rliegmann/PixelIt#3]
Hi, I have tried to build your fork with Platformio which was successful. After flashing this firmware to the ESP8266 (WemosD1Mini) the Matrix stays dark. Flashing the original firmware it instantly shows text again.
Do you mind what I may have done wrong?

Maybe we can find to have a quick chat sometimes..

All the Best,
Sebastian

**Comment by rliegmann** [comment]
Hello Sebatian,

Apologies for the late reply. Unfortunately I only just saw it.
Do you have any output on the serial interface? You may have already found a solution.

With best regards
Ralf
